// Generated by CoffeeScript 1.6.3
(function() {
  var CHARA_SIZE, GAME_HEIGHT, GAME_WIDTH;

  enchant();

  CHARA_SIZE = 32;

  GAME_WIDTH = 320;

  GAME_HEIGHT = 320;

  window.onload = function() {
    var Box, game;
    game = new Game(GAME_WIDTH, GAME_HEIGHT);
    game.preload('img/box.png');
    Box = enchant.Class.create(enchant.Sprite, {
      initialize: function() {
        enchant.Sprite.call(this, CHARA_SIZE, CHARA_SIZE);
        this.x = GAME_WIDTH;
        this.y = Math.floor(Math.random() * GAME_HEIGHT);
        this.image = game.assets['img/box.png'];
        this.addEventListener('enterframe', this.update);
        return game.rootScene.addChild(this);
      },
      update: function() {
        this.x -= 0.1;
        return this.frame = [0, 1, 0, 2][this.age % 4];
      }
    });
    game.onload = function() {
      game.rootScene.addEventListener('touchstart', function(e) {});
      game.rootScene.addEventListener('touchend', function(e) {});
      return new Box;
    };
    return game.start();
  };

}).call(this);
